{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-thymeleaf",
    "version": "3.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.4.1"
          }
        },
        {
          "group": "org.thymeleaf",
          "module": "thymeleaf-spring6",
          "version": {
            "requires": "3.1.3.RELEASE"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-thymeleaf-3.4.1.jar",
          "url": "spring-boot-starter-thymeleaf-3.4.1.jar",
          "size": 4770,
          "sha512": "98c0c63094fee526bb70407c5249608bfecd7e4bce7641c2659c10863f557b4bc837bf83fc4c1fb73f31c93f7774f52289e5bf4c9e2b66ff8d7c3df526977c8d",
          "sha256": "ba98f3090c28f9c47903f2165b842a5d14b7bfc155e3bfc0170b6d85d0fbda4d",
          "sha1": "a2903c33815dbc9c65c97f83e32dcea2d9935429",
          "md5": "aface3723dca8c0c2045afeb77daa27d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.4.1"
          }
        },
        {
          "group": "org.thymeleaf",
          "module": "thymeleaf-spring6",
          "version": {
            "requires": "3.1.3.RELEASE"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-thymeleaf-3.4.1.jar",
          "url": "spring-boot-starter-thymeleaf-3.4.1.jar",
          "size": 4770,
          "sha512": "98c0c63094fee526bb70407c5249608bfecd7e4bce7641c2659c10863f557b4bc837bf83fc4c1fb73f31c93f7774f52289e5bf4c9e2b66ff8d7c3df526977c8d",
          "sha256": "ba98f3090c28f9c47903f2165b842a5d14b7bfc155e3bfc0170b6d85d0fbda4d",
          "sha1": "a2903c33815dbc9c65c97f83e32dcea2d9935429",
          "md5": "aface3723dca8c0c2045afeb77daa27d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-thymeleaf-3.4.1-javadoc.jar",
          "url": "spring-boot-starter-thymeleaf-3.4.1-javadoc.jar",
          "size": 4770,
          "sha512": "98c0c63094fee526bb70407c5249608bfecd7e4bce7641c2659c10863f557b4bc837bf83fc4c1fb73f31c93f7774f52289e5bf4c9e2b66ff8d7c3df526977c8d",
          "sha256": "ba98f3090c28f9c47903f2165b842a5d14b7bfc155e3bfc0170b6d85d0fbda4d",
          "sha1": "a2903c33815dbc9c65c97f83e32dcea2d9935429",
          "md5": "aface3723dca8c0c2045afeb77daa27d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-thymeleaf-3.4.1-sources.jar",
          "url": "spring-boot-starter-thymeleaf-3.4.1-sources.jar",
          "size": 4770,
          "sha512": "98c0c63094fee526bb70407c5249608bfecd7e4bce7641c2659c10863f557b4bc837bf83fc4c1fb73f31c93f7774f52289e5bf4c9e2b66ff8d7c3df526977c8d",
          "sha256": "ba98f3090c28f9c47903f2165b842a5d14b7bfc155e3bfc0170b6d85d0fbda4d",
          "sha1": "a2903c33815dbc9c65c97f83e32dcea2d9935429",
          "md5": "aface3723dca8c0c2045afeb77daa27d"
        }
      ]
    }
  ]
}
