#spring:
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create
#    database: h2
#    properties:
#      hibernate:
#        format_sql: true
#        use_sql_comments: true
#        highlight_sql: true
#
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#      settings:
#        web-allow-others: true
#
#  datasource:
#    url: jdbc:h2:mem:testdb;DATABASE_TO_UPPER=FALSE;
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:

spring:
  h2:
    console:
      enabled: true
  application:
    name: NBE3-4-1-Team02
  datasource:
    url: jdbc:h2:file:C:/Users/sia54/local;DB_CLOSE_DELAY=-1;MODE=MySql
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: h2
server:
  servlet:
    context-path: /api/v1
  profiles:
    active: dev-geonHui
