spring:
  application:
    name: NBE3-4-1-Team02
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=MySql
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    database: h2
    properties:
      hibernate:
        auto_quote_keyword: true
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
    defer-datasource-initialization: true
server:
  servlet:
    context-path: /api/v1
default:
  delivery:
    hour: 14
    minute : 0