#spring:
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create
#    database: h2
#    properties:
#      hibernate:
#        format_sql: true
#        use_sql_comments: true
#        highlight_sql: true
#
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#      settings:
#        web-allow-others: true
#
#  datasource:
#    url: jdbc:h2:mem:testdb;DATABASE_TO_UPPER=FALSE;
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:

spring:
  application:
    name: NBE3-4-1-Team02
#  datasource:
#    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=MySql
  datasource:
    url: jdbc:h2:mem:product_db;DB_CLOSE_ON_EXIT=FALSE;MODE=MySql  # DB 유지, 새로운이름
    driverClassName: org.h2.Driver
    username: sa
    password:
    initialize: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    database: h2
  h2:
    console:
        enabled: true
        path: /h2-console
server:
  port: 8080
  servlet:
    context-path: /api/v1