spring:
  h2:
    console:
      enabled: true
  application:
    name: NBE3-4-1-Team02
  datasource:
    url: jdbc:h2:file:C:/Users/sia54/local;DB_CLOSE_DELAY=-1;MODE=MySql
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: h2
server:
  servlet:
    context-path: /api/v1
jwt:
      secret: "Z2F0Z2F0Z2F0Z2F0Z2F0Z2F0Z2F0Z2F0Z2F0Z2F0Z2F0Z2F0Z2F0Z2F0Z2F0Z2F0"
      token-validity-in-milliseconds: 1800000