spring:
  application:
    name: NBE3-4-1-Team02
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=MySql
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: h2
  h2:
    console:
        enabled: true
        path: /h2-console
server:
  port: 8080
  servlet:
    context-path: /api/v1